"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,Ban,Bell,Bot,BrainCircuit,CalendarCheck,ChevronRight,Clock,Headphones,History,LayoutDashboard,Menu,MessageSquare,Mic,Pause,Phone,PhoneCall,Play,Plus,Search,Settings,ShieldCheck,Sparkles,TrendingUp,UserRound,Users,Volume2,Waves,Wifi,X,Zap} from "lucide-react";
import {calls,campaigns} from "@/lib/mock";

type Call={id:number;name:string;number:string;type:string;status:string;duration:string;intent:string;sentiment:string;score:number};

const nav=[["Overview",LayoutDashboard],["Outbound",PhoneCall],["Inbound",Phone],["Agents",Bot],["Analytics",TrendingUp],["Call History",History],["Settings",Settings]] as const;

export default function Home(){
 const[active,setActive]=useState("Overview"); const[mobile,setMobile]=useState(false);
 const[call,setCall]=useState<Call|null>(null); const[callMode,setCallMode]=useState<"outbound"|"inbound">("outbound");
 const[running,setRunning]=useState(false); const[seconds,setSeconds]=useState(0); const[stage,setStage]=useState("Ready");
 const[toast,setToast]=useState(""); const[search,setSearch]=useState(""); const[showCampaign,setShowCampaign]=useState(false);
 const[campaignRunning,setCampaignRunning]=useState(false);

 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[running]);
 function notify(s:string){setToast(s);setTimeout(()=>setToast(""),2200)}
 function startCall(c:Call,mode:"outbound"|"inbound"){setCall(c);setCallMode(mode);setRunning(true);setSeconds(0);setStage(mode==="outbound"?"Dialing":"Incoming call");setTimeout(()=>setStage("Connected"),1100);setTimeout(()=>setStage("AI speaking"),2200);setTimeout(()=>setStage("Listening"),3900);setTimeout(()=>setStage("Understanding intent"),5600);setTimeout(()=>setStage("Qualified"),7300)}
 function endCall(){setRunning(false);setStage("Completed");notify("Call completed and outcome saved")}
 function startCampaign(){setCampaignRunning(true);notify("Outbound campaign started");setTimeout(()=>setCampaignRunning(false),8000)}
 const filtered=calls.filter(c=>`${c.name} ${c.number} ${c.intent}`.toLowerCase().includes(search.toLowerCase()));

 return <div className="min-h-screen bg-[#070707] text-zinc-100">
  <aside className={`fixed inset-y-0 left-0 z-50 w-[250px] border-r border-[#25272c] bg-[#090a0b] p-4 ${mobile?"block":"hidden"} lg:block`}>
   <div className="flex items-center justify-between px-2 py-2"><div className="flex items-center gap-2 font-bold"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-black"><Headphones size={19}/></div>Nexora Voice</div><button className="lg:hidden" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <div className="mt-8 space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>{setActive(n);setMobile(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm ${active===n?"bg-white text-black":"text-zinc-400 hover:bg-white/[.05] hover:text-white"}`}><I size={17}/>{n}</button>)}</div>
   <div className="absolute bottom-4 left-4 right-4 rounded-2xl border border-[#25272c] bg-[#111214] p-4"><div className="flex items-center gap-2 text-xs font-bold"><Wifi size={13} className="pulse"/> DEMO VOICE SYSTEM</div><p className="mt-2 text-[11px] leading-5 text-zinc-500">Calls, speech and AI outcomes are simulated. Connect telephony, STT, LLM and TTS through your backend later.</p></div>
  </aside>

  <div className="lg:pl-[250px]"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-[#25272c] bg-[#070707]/90 px-5 backdrop-blur-xl">
   <button className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="hidden items-center gap-2 text-xs text-zinc-500 sm:flex"><ShieldCheck size={14}/> Voice operations <span className="text-zinc-700">/</span> Live demo</div>
   <div className="flex items-center gap-3"><button onClick={()=>notify("No new alerts")} className="rounded-xl border border-[#25272c] p-2"><Bell size={16}/></button><div className="grid h-8 w-8 place-items-center rounded-full bg-white text-xs font-black text-black">HA</div></div>
  </header>

  <main className="grid-bg min-h-[calc(100vh-64px)] p-4 md:p-7">
   {active==="Overview"&&<Overview onStart={startCall} campaignRunning={campaignRunning} startCampaign={startCampaign} setActive={setActive}/>}
   {active==="Outbound"&&<Outbound onStart={c=>startCall(c,"outbound")} campaignRunning={campaignRunning} startCampaign={startCampaign} showCampaign={showCampaign} setShowCampaign={setShowCampaign}/>}
   {active==="Inbound"&&<Inbound onStart={c=>startCall(c,"inbound")}/>}
   {active==="Agents"&&<Agents notify={notify}/>}
   {active==="Analytics"&&<Analytics/>}
   {active==="Call History"&&<HistoryPage search={search} setSearch={setSearch} calls={filtered}/>}
   {active==="Settings"&&<SettingsPage notify={notify}/>}
  </main></div>

  {call&&<CallModal call={call} mode={callMode} running={running} seconds={seconds} stage={stage} onEnd={endCall} onClose={()=>{setCall(null);setRunning(false)}}/>}
  {toast&&<div className="fixed bottom-5 right-5 z-[80] rounded-xl bg-white px-4 py-3 text-xs font-bold text-black shadow-2xl">{toast}</div>}
 </div>
}

function Shell({title,subtitle,children,action}:{title:string;subtitle:string;children:React.ReactNode;action?:React.ReactNode}){return <div className="mx-auto max-w-[1400px] fade"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-zinc-500">AI voice operations</div><h1 className="mt-2 text-3xl font-black md:text-5xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">{subtitle}</p></div>{action}</div>{children}</div>}

function Overview({onStart,campaignRunning,startCampaign,setActive}:{onStart:(c:Call,m:"outbound"|"inbound")=>void;campaignRunning:boolean;startCampaign:()=>void;setActive:(s:string)=>void}){
 return <Shell title="Voice operations" subtitle="Manage outbound campaigns and inbound AI responders from one workspace." action={<button onClick={()=>setActive("Outbound")} className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-black">Create campaign</button>}>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Calls today","248","+18.4%",PhoneCall],["Connected","173","69.8%",Wifi],["Interested","42","24.3%",TrendingUp],["Follow-ups","31","74% completed",CalendarCheck]].map(([a,b,c,I])=><div key={String(a)} className="rounded-2xl border border-[#25272c] bg-[#0d0e10] p-5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-black"><I size={17}/></div><p className="mt-5 text-sm text-zinc-500">{String(a)}</p><p className="mt-1 text-3xl font-black">{String(b)}</p><p className="mt-2 text-xs font-bold text-zinc-400">{String(c)}</p></div>)}</div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
   <div className="glow rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Live call activity</h2><p className="text-xs text-zinc-500">AI agents handling conversations</p></div><span className="flex items-center gap-2 text-[10px] font-bold"><span className="h-2 w-2 rounded-full bg-white pulse"/> LIVE</span></div>
    <div className="mt-5 grid gap-3">{calls.slice(0,3).map((c,i)=><div key={c.id} className="flex flex-col gap-3 rounded-2xl border border-[#222429] bg-[#090a0b] p-4 sm:flex-row sm:items-center"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-black"><UserRound size={18}/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold">{c.name}</p><span className="rounded-full bg-white/[.06] px-2 py-1 text-[9px] font-bold">{c.type}</span></div><p className="mt-1 text-xs text-zinc-500">{c.number} · {c.intent}</p></div><div className="text-left sm:text-right"><p className="text-xs font-bold">{c.status}</p><p className="mt-1 text-[10px] text-zinc-600">{c.duration}</p></div><button onClick={()=>onStart(c,i%2?"inbound":"outbound")} className="rounded-xl border border-[#303238] px-3 py-2 text-xs font-bold hover:bg-white hover:text-black">Open call</button></div>)}</div>
   </div>
   <div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Outbound engine</h2><p className="text-xs text-zinc-500">Campaign control</p></div><PhoneCall size={17}/></div><div className="mt-6 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full border border-white/20 bg-white/[.05]"><PhoneCall size={26}/></div><p className="mt-5 text-lg font-black">{campaignRunning?"Campaign running":"Ready to call"}</p><p className="mt-1 text-xs text-zinc-500">{campaignRunning?"AI agents are processing the lead queue":"Start a simulated outbound campaign"}</p></div><button onClick={startCampaign} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 text-sm font-black text-black">{campaignRunning?<><Pause size={15}/> Campaign active</>:<><Play size={15} fill="currentColor"/> Start campaign</>}</button></div>
  </div>
 </Shell>
}

function Outbound({onStart,campaignRunning,startCampaign,showCampaign,setShowCampaign}:{onStart:(c:Call)=>void;campaignRunning:boolean;startCampaign:()=>void;showCampaign:boolean;setShowCampaign:(x:boolean)=>void}){
 return <Shell title="Outbound AI" subtitle="Launch campaigns, watch AI calls progress and inspect qualification outcomes." action={<button onClick={()=>setShowCampaign(true)} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-black text-black"><Plus size={16}/> New campaign</button>}>
  <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="space-y-5"><div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Campaigns</h2><p className="text-xs text-zinc-500">Simulated outbound lead queues</p></div><span className="text-xs text-zinc-500">2 active</span></div><div className="mt-5 space-y-3">{campaigns.map(c=><div key={c.name} className="rounded-2xl border border-[#222429] bg-[#090a0b] p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-bold text-sm">{c.name}</p><p className="mt-1 text-xs text-zinc-500">{c.leads.toLocaleString()} leads · {c.status}</p></div><button onClick={startCampaign} className="rounded-xl border border-[#303238] px-3 py-2 text-xs font-bold hover:bg-white hover:text-black">{campaignRunning&&c.status==="Running"?"Running":"Start"}</button></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#202226]"><div className="h-full rounded-full bg-white transition-all" style={{width:`${c.contacted}%`}}/></div><div className="mt-3 grid grid-cols-3 text-[10px] text-zinc-500"><span>{c.contacted}% contacted</span><span>{c.interested}% interested</span><span>{c.followups}% follow-up</span></div></div>)}</div></div>
  <div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Lead queue</h2><p className="text-xs text-zinc-500">Click a lead to simulate a live call</p></div><span className="text-xs text-zinc-500">248 ready</span></div><div className="mt-4 grid gap-2 md:grid-cols-2">{calls.filter(c=>c.type==="Outbound").map(c=><button key={c.id} onClick={()=>onStart(c)} className="flex items-center gap-3 rounded-2xl border border-[#222429] bg-[#090a0b] p-3 text-left hover:border-white/30"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-black"><UserRound size={15}/></div><div className="flex-1"><p className="text-xs font-bold">{c.name}</p><p className="text-[10px] text-zinc-600">{c.number}</p></div><PhoneCall size={15}/></button>)}</div></div></div>
  <div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><p className="text-xs font-bold uppercase tracking-widest text-zinc-500">Agent</p><div className="mt-4 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-black"><Bot size={22}/></div><div><p className="font-bold">Sharvani</p><p className="text-xs text-zinc-500">Indian Female · English + Hindi + Telugu</p></div></div><div className="mt-5 space-y-2 text-xs">{["Qualify lead","Capture requirements","Answer FAQs","Schedule follow-up","Human handoff"].map(x=><div key={x} className="flex items-center gap-2 rounded-xl bg-white/[.04] p-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-black"><Zap size={11}/></span>{x}</div>)}</div></div></div>
  {showCampaign&&<Modal title="Create outbound campaign" onClose={()=>setShowCampaign(false)}><div className="space-y-4"><label className="block text-xs font-bold">Campaign name<input defaultValue="New Property Leads" className="mt-2 w-full rounded-xl border border-[#303238] bg-[#090a0b] p-3 outline-none"/></label><label className="block text-xs font-bold">Agent<select className="mt-2 w-full rounded-xl border border-[#303238] bg-[#090a0b] p-3 outline-none"><option>Sharvani — Indian Female</option><option>Arjun — Indian Male</option></select></label><button onClick={()=>{setShowCampaign(false);startCampaign()}} className="w-full rounded-xl bg-white py-3 text-sm font-black text-black">Create & start campaign</button></div></Modal>}
 </Shell>
}

function Inbound({onStart}:{onStart:(c:Call)=>void}){
 const inbound=calls.filter(c=>c.type==="Inbound"); return <Shell title="Inbound AI" subtitle="AI responders answer incoming calls, detect intent and recommend the next action." action={<div className="flex items-center gap-2 rounded-xl border border-[#292b30] bg-[#0d0e10] px-3 py-2 text-xs"><span className="h-2 w-2 rounded-full bg-white pulse"/> Responder online</div>}>
  <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Incoming calls</h2><p className="text-xs text-zinc-500">Click to open a live AI conversation</p></div><Phone size={18}/></div><div className="mt-5 space-y-3">{inbound.map(c=><div key={c.id} className="flex items-center gap-3 rounded-2xl border border-[#222429] bg-[#090a0b] p-4"><div className="relative grid h-11 w-11 place-items-center rounded-xl bg-white text-black"><Phone size={17}/><span className="absolute -right-1 -top-1 h-3 w-3 rounded-full bg-white pulse"/></div><div className="flex-1"><p className="text-sm font-bold">{c.name}</p><p className="text-xs text-zinc-500">{c.number} · {c.intent}</p></div><button onClick={()=>onStart(c)} className="rounded-xl bg-white px-3 py-2 text-xs font-black text-black">Answer</button></div>)}</div></div>
  <div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-6"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full border border-white/15 bg-white/[.05]"><div className="grid h-16 w-16 place-items-center rounded-full bg-white text-black"><Mic size={27}/></div></div><div className="mt-5 text-center"><p className="text-xl font-black">AI Responder</p><p className="mt-1 text-xs text-zinc-500">Always-on inbound voice agent</p></div><div className="mt-7 grid grid-cols-2 gap-3">{[["Calls answered","67"],["Avg. response","1.2s"],["Resolved","82%"],["Human handoff","11%"]].map(x=><div key={x[0]} className="rounded-2xl border border-[#222429] p-4"><p className="text-[10px] text-zinc-500">{x[0]}</p><p className="mt-1 text-xl font-black">{x[1]}</p></div>)}</div></div></div>
 </Shell>
}

function Agents({notify}:{notify:(s:string)=>void}){return <Shell title="Voice agents" subtitle="Configure the personality, voice, languages and actions available to each agent."><div className="grid gap-4 md:grid-cols-2">{[["Sharvani","Outbound Sales Representative","Indian Female","English · Hindi · Telugu"],["Arjun","Inbound Support Responder","Indian Male","English · Hindi · Telugu"]].map((a,i)=><div key={a[0]} className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-black"><Bot/></div><div><h2 className="font-bold">{a[0]}</h2><p className="text-xs text-zinc-500">{a[1]}</p></div><span className="ml-auto rounded-full bg-white px-2 py-1 text-[9px] font-black text-black">ACTIVE</span></div><div className="mt-6 space-y-2 text-xs">{[["Voice",a[2]],["Languages",a[3]],["Temperature","0.4"],["Human handoff","Enabled"]].map(x=><div key={x[0]} className="flex justify-between rounded-xl bg-white/[.04] p-3"><span className="text-zinc-500">{x[0]}</span><b>{x[1]}</b></div>)}</div><button onClick={()=>notify(`${a[0]} configuration opened`)} className="mt-5 w-full rounded-xl border border-[#303238] py-2.5 text-xs font-bold hover:bg-white hover:text-black">Configure agent</button></div>)}</div></Shell>}

function Analytics(){return <Shell title="Call analytics" subtitle="Understand call volume, connection rates and AI qualification performance."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total calls","1,842"],["Connected","1,264"],["Interested","328"],["Conversions","84"]].map(x=><div key={x[0]} className="rounded-2xl border border-[#25272c] bg-[#0d0e10] p-5"><p className="text-xs text-zinc-500">{x[0]}</p><p className="mt-2 text-3xl font-black">{x[1]}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><h2 className="font-bold">Connection performance</h2><div className="mt-7 flex h-48 items-end gap-2">{[32,48,41,64,58,74,69,82,71,91,77,96].map((v,i)=><div key={i} className="group flex flex-1 flex-col justify-end"><div className="w-full rounded-t-lg bg-white/80 transition group-hover:bg-white" style={{height:`${v}%`}}/></div>)}</div><div className="mt-3 flex justify-between text-[9px] text-zinc-600"><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span></div></div><div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><h2 className="font-bold">Outcome distribution</h2><div className="mt-6 space-y-4">{([["Interested",42],["Follow-up",31],["Not interested",17],["Unreachable",10]] as [string, number][]).map(x=><div key={x[0]}><div className="flex justify-between text-xs"><span>{x[0]}</span><span className="text-zinc-500">{x[1]}%</span></div><div className="mt-2 h-2 rounded-full bg-[#202226]"><div className="h-full rounded-full bg-white" style={{width:`${x[1]*2}%`}}/></div></div>)}</div></div></div></Shell>}

function HistoryPage({search,setSearch,calls}:{search:string;setSearch:(s:string)=>void;calls:Call[]}){return <Shell title="Call history" subtitle="Search conversations and inspect the outcome captured by the AI."><div className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><div className="flex items-center gap-2 rounded-xl border border-[#25272c] bg-[#090a0b] px-3 py-2 md:max-w-md"><Search size={15} className="text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search caller, number or intent..." className="w-full bg-transparent text-xs outline-none"/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-[#25272c] text-[10px] uppercase tracking-widest text-zinc-600"><tr><th className="p-3">Caller</th><th className="p-3">Direction</th><th className="p-3">Intent</th><th className="p-3">Sentiment</th><th className="p-3">Score</th><th className="p-3">Outcome</th></tr></thead><tbody className="divide-y divide-[#181a1d]">{calls.map(c=><tr key={c.id} className="hover:bg-white/[.025]"><td className="p-4"><b>{c.name}</b><p className="mt-1 text-[10px] text-zinc-600">{c.number}</p></td><td className="p-4">{c.type}</td><td className="p-4">{c.intent}</td><td className="p-4">{c.sentiment}</td><td className="p-4 font-bold">{c.score}%</td><td className="p-4"><span className="rounded-full bg-white/[.06] px-2 py-1 font-bold">{c.status}</span></td></tr>)}</tbody></table></div></div></Shell>}

function SettingsPage({notify}:{notify:(s:string)=>void}){return <Shell title="Voice settings" subtitle="Demo configuration for telephony, speech, language and AI behavior."><div className="grid gap-5 lg:grid-cols-2">{[["Telephony","Provider","Demo SIP / Telephony","Phone number","+91 90000 00000"],["Speech","STT","Whisper-style transcription","TTS","Indian English Female"],["AI","Model","Agentic LLM","Temperature","0.4"],["Safety","Human handoff","Enabled","Call recording","Demo only"]].map(g=><div key={g[0]} className="rounded-3xl border border-[#292b30] bg-[#0c0d0f] p-5"><h2 className="font-bold">{g[0]}</h2><div className="mt-4 space-y-2">{[g.slice(1,3),g.slice(3,5)].map((x,i)=><div key={i} className="flex justify-between rounded-xl bg-white/[.04] p-3 text-xs"><span className="text-zinc-500">{x[0]}</span><b>{x[1]}</b></div>)}</div></div>)}</div><button onClick={()=>notify("Settings saved in demo mode")} className="mt-5 rounded-xl bg-white px-5 py-2.5 text-xs font-black text-black">Save configuration</button></Shell>}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/60 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-[#303238] bg-[#0d0e10] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-bold">{title}</h2><button onClick={onClose}><X size={18}/></button></div><div className="mt-6">{children}</div></div></div>}

function CallModal({call,mode,running,seconds,stage,onEnd,onClose}:{call:Call;mode:"outbound"|"inbound";running:boolean;seconds:number;stage:string;onEnd:()=>void;onClose:()=>void}){
 const bars=Array.from({length:28}); const transcript=mode==="outbound"?[
  ["AI","Hi Rahul, I'm Sharvani calling regarding properties in Tellapur."],
  ["Caller","Yes, I'm looking for a 3 BHK. Can you share some options?"],
  ["AI","Absolutely. What budget range are you considering?"],
  ["Caller","Around one point two to one point five crore."],
  ["AI","Thanks. I can arrange a site visit for you. Would this weekend work?"]
 ]:[
  ["Caller","I'm interested in a 3 BHK apartment in Tellapur. What is the price?"],
  ["AI","We have 3 BHK options starting around ₹1.2 crore. Would you like available projects?"],
  ["Caller","Yes, and I'd like to know about a site visit."],
  ["AI","I can help schedule that. What day works best for you?"]
 ];
 return <div className="fixed inset-0 z-[60] bg-black/80 p-2 backdrop-blur-md md:p-8"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-3xl border border-[#303238] bg-[#0a0b0c] shadow-2xl">
  <div className="flex items-center justify-between border-b border-[#25272c] px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-black"><Phone size={17}/></div><div><p className="text-sm font-bold">{mode==="outbound"?"Outbound AI Call":"Inbound AI Responder"}</p><p className="text-[10px] text-zinc-600">{stage} · {String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</p></div></div><button onClick={onClose}><X size={20}/></button></div>
  <div className="grid min-h-0 flex-1 lg:grid-cols-[1fr_360px]"><div className="min-h-0 overflow-y-auto p-5 md:p-7"><div className="flex flex-col items-center"><div className={`relative grid h-24 w-24 place-items-center rounded-full border border-white/20 bg-white/[.05] ${running?"pulse":""}`}><div className="grid h-16 w-16 place-items-center rounded-full bg-white text-black"><UserRound size={28}/></div></div><h2 className="mt-4 text-xl font-black">{call.name}</h2><p className="text-xs text-zinc-500">{call.number} · {call.intent}</p><div className="mt-6 flex h-12 items-center gap-1">{bars.map((_,i)=><span key={i} className={`${running?"wave":"h-2"} w-1 rounded-full bg-white/80`} style={{animationDelay:`${i*35}ms`}}/>)}</div><div className="mt-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-zinc-500">{running?<><span className="h-2 w-2 rounded-full bg-white pulse"/>{stage}</>:<><CheckIcon/> {stage}</>}</div></div>
   <div className="mx-auto mt-8 max-w-2xl space-y-3">{transcript.map((x,i)=><div key={i} className={`slide flex ${x[0]==="AI"?"justify-start":"justify-end"}`}><div className={`max-w-[85%] rounded-2xl border border-[#25272c] p-4 ${x[0]==="AI"?"bg-[#111214]":"bg-white text-black"}`}><p className="mb-1 text-[9px] font-black uppercase tracking-widest opacity-50">{x[0]}</p><p className="text-xs leading-5">{x[1]}</p></div></div>)}</div>
  </div><aside className="border-t border-[#25272c] bg-[#0d0e10] p-5 lg:border-l lg:border-t-0"><p className="text-[10px] font-black uppercase tracking-widest text-zinc-600">AI insights</p><div className="mt-4 space-y-3">{[["Intent",call.intent,"92%"],["Sentiment",call.sentiment,""],["Interest","High","94%"],["Budget","₹1.2–1.5 Cr",""],["Next action","Schedule site visit",""]].map(x=><div key={x[0]} className="rounded-2xl border border-[#25272c] p-4"><div className="flex justify-between text-[10px] text-zinc-500"><span>{x[0]}</span><span>{x[2]}</span></div><p className="mt-1 text-sm font-black">{x[1]}</p>{x[2]&&<div className="mt-3 h-1.5 rounded-full bg-[#202226]"><div className="h-full rounded-full bg-white" style={{width:x[2]}}/></div>}</div>)}</div><div className="mt-5 rounded-2xl border border-white/15 bg-white/[.04] p-4"><div className="flex items-center gap-2 text-xs font-bold"><Sparkles size={14}/> Agent recommendation</div><p className="mt-2 text-xs leading-5 text-zinc-500">Lead is highly engaged. Offer a site visit and save the requirement in CRM.</p></div><button onClick={onEnd} disabled={!running} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 text-xs font-black text-black disabled:opacity-40">{running?<><Ban size={14}/> End call</>:<><CheckIcon/> Call saved</>}</button></aside></div>
 </div></div>
}
function CheckIcon(){return <span className="grid h-3.5 w-3.5 place-items-center rounded-full bg-white text-black"><Zap size={8}/></span>}
